### PR TITLE
Add Kind constraint

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@plbt5 , this is ready for review and merge.

**Review by plbt5 — APPROVED** [review]
I don't fully get the python code, but the rest is understood and correct.

**Comment by plbt5** [comment]
I can only review; I seem to be limited in write access to this repo, hence cannot do no merging.

**Comment by ajnelson-nist** [comment]
> I can only review; I seem to be limited in write access to this repo, hence cannot do no merging.

Sorry, try now.

**Pull request merged**
